seed: 123

series:
  - id: http-outbound
    name: 'jmx-server-metrics-previous-http'
    tags:
      type: 'outbound'
      host: '{{.host}}'
      region: '{{.region}}'
      pod: 'rgw{{printf "%03.f" .podNum}}ea'
      target_host: 'www.toolkit.mapquestapi.com'
      target_ipaddr: '205.188.201.151'
      target_port:  '80'
    fields:
      2xx: 'int'
      4xx: 'int'
      5xx: 'int'
      latency_99: 'float'
    variables:
      - name: host
        values:
          - 'abc000wo.us-west-2.e2e.4.apigee.com'
          - 'rmp147ea.us-ea.4.apigee.com'
      - name: region
        values:
          - 'us-east-1'
          - 'us-west-2'
      - name: podNum
        from: 0
        to: 3
        step: 1
